"""
Bilingual degree programs data for the LLM evaluation system.
This file contains all the specific degree programs with their relevant industries and roles
in both Finnish and English for comprehensive bilingual matching.
"""

DEGREE_PROGRAMS = {
    # Information Technology Degrees
    "bachelor_of_engineering_information_technology": {
        "name": "Bachelor of Engineering (BEng), Information Technology",
        "fields": ["Bachelor of Engineering (BEng), Information Technology"],
        "relevant_industries": [
            "teknologia",
            "ohjelmisto",
            "konsultointi",
            "rahoitus",
            "terveydenhuolto",
            "koulutus",
            "tietoliikenne",
            "tietotekniikka",
            "tietojärjestelmät",
            "tietoturva",
            "tietohallinto",
            "IT",
            "information technology",
            "software",
            "consulting",
            "finance",
            "healthcare",
            "education",
            "telecommunications",
            "information systems",
            "information security",
            "information management",
        ],
        "relevant_roles": [
            "ohjelmistokehitys",
            "ohjelmistokehittäjä",
            "ohjelmointi",
            "web-kehitys",
            "mobiilikehitys",
            "sovelluskehitys",
            "järjestelmänhallinta",
            "tietokantojen hallinta",
            "verkkohallinta",
            "tietoturva",
            "tietojen analysointi",
            "tietotuki",
            "tekniikkatuki",
            "tietojenkäsittely",
            "digitaalinen muutos",
            "pilvipalvelut",
            "tekoäly",
            "koneoppiminen",
            "tietoarkkitehtuuri",
            "tietojen visualisointi",
            "kehittäjä",
            "ohjelmoija",
            "järjestelmäasiantuntija",
            "tietokanta-asiantuntija",
            "verkkoasiantuntija",
            "tietoturva-asiantuntija",
            "tietoanalyytikko",
            "tietojärjestelmäasiantuntija",
            "software development",
            "software engineering",
            "web development",
            "mobile development",
            "full stack development",
            "front end development",
            "back end development",
            "mobile app development",
            "web app development",
            "programming",
            "system administration",
            "database management",
            "network administration",
            "cybersecurity",
            "data analysis",
            "IT support",
            "technical support",
            "data science",
            "information systems",
            "digital transformation",
            "cloud computing",
            "AI",
            "machine learning",
            "data engineering",
            "data visualization",
            "data architecture",
            "data security",
            "data governance",
        ],
    },
    "insinoori_tieto_ja_viestintatekniikka": {
        "name": "Insinööri (AMK), tieto- ja viestintätekniikka",
        "fields": ["Insinööri (AMK), tieto- ja viestintätekniikka"],
        "relevant_industries": [
            "teknologia",
            "ohjelmisto",
            "konsultointi",
            "rahoitus",
            "terveydenhuolto",
            "koulutus",
            "tietoliikenne",
            "tietotekniikka",
            "tietojärjestelmät",
            "tietoturva",
            "tietohallinto",
            "IT",
            "information technology",
            "software",
            "consulting",
            "finance",
            "healthcare",
            "education",
            "telecommunications",
            "information systems",
            "information security",
            "information management",
        ],
        "relevant_roles": [
            "ohjelmistokehitys",
            "ohjelmistokehittäjä",
            "ohjelmointi",
            "web-kehitys",
            "mobiilikehitys",
            "sovelluskehitys",
            "järjestelmänhallinta",
            "tietokantojen hallinta",
            "verkkohallinta",
            "tietoturva",
            "tietojen analysointi",
            "tietotuki",
            "tekniikkatuki",
            "tietojenkäsittely",
            "digitaalinen muutos",
            "pilvipalvelut",
            "tekoäly",
            "koneoppiminen",
            "tietoarkkitehtuuri",
            "tietojen visualisointi",
            "kehittäjä",
            "ohjelmoija",
            "järjestelmäasiantuntija",
            "tietokanta-asiantuntija",
            "verkkoasiantuntija",
            "tietoturva-asiantuntija",
            "tietoanalyytikko",
            "tietojärjestelmäasiantuntija",
            "software development",
            "software engineering",
            "web development",
            "mobile development",
            "full stack development",
            "front end development",
            "back end development",
            "mobile app development",
            "web app development",
            "programming",
            "system administration",
            "database management",
            "network administration",
            "cybersecurity",
            "data analysis",
            "IT support",
            "technical support",
            "data science",
            "information systems",
            "digital transformation",
            "cloud computing",
            "AI",
            "machine learning",
            "data engineering",
            "data visualization",
            "data architecture",
            "data security",
            "data governance",
        ],
    },
    "tradenomi_tietojenkasittely": {
        "name": "Tradenomi (AMK), tietojenkäsittely",
        "fields": ["Tradenomi (AMK), tietojenkäsittely"],
        "relevant_industries": [
            "teknologia",
            "ohjelmisto",
            "konsultointi",
            "rahoitus",
            "terveydenhuolto",
            "koulutus",
            "tietoliikenne",
            "tietotekniikka",
            "tietojärjestelmät",
            "tietoturva",
            "tietohallinto",
            "IT",
            "information technology",
            "software",
            "consulting",
            "finance",
            "healthcare",
            "education",
            "telecommunications",
            "information systems",
            "information security",
            "information management",
        ],
        "relevant_roles": [
            "ohjelmistokehitys",
            "ohjelmistokehittäjä",
            "ohjelmointi",
            "web-kehitys",
            "mobiilikehitys",
            "sovelluskehitys",
            "järjestelmänhallinta",
            "tietokantojen hallinta",
            "verkkohallinta",
            "tietoturva",
            "tietojen analysointi",
            "tietotuki",
            "tekniikkatuki",
            "tietojenkäsittely",
            "digitaalinen muutos",
            "pilvipalvelut",
            "tekoäly",
            "koneoppiminen",
            "tietoarkkitehtuuri",
            "tietojen visualisointi",
            "kehittäjä",
            "ohjelmoija",
            "järjestelmäasiantuntija",
            "tietokanta-asiantuntija",
            "verkkoasiantuntija",
            "tietoturva-asiantuntija",
            "tietoanalyytikko",
            "tietojärjestelmäasiantuntija",
            "software development",
            "software engineering",
            "web development",
            "mobile development",
            "full stack development",
            "front end development",
            "back end development",
            "mobile app development",
            "web app development",
            "programming",
            "system administration",
            "database management",
            "network administration",
            "cybersecurity",
            "data analysis",
            "IT support",
            "technical support",
            "data science",
            "information systems",
            "digital transformation",
            "cloud computing",
            "AI",
            "machine learning",
            "data engineering",
            "data visualization",
            "data architecture",
            "data security",
            "data governance",
        ],
    },
    # Business Administration Degrees
    "bachelor_of_business_administration_international_business": {
        "name": "Bachelor of Business Administration (BBA), International Business",
        "fields": ["Bachelor of Business Administration (BBA), International Business"],
        "relevant_industries": [
            "liiketalous",
            "kansainvälinen kauppa",
            "rahoitus",
            "konsultointi",
            "logistiikka",
            "markkinointi",
            "myynti",
            "vienti",
            "tuonti",
            "business",
            "international trade",
            "finance",
            "consulting",
            "logistics",
            "marketing",
            "sales",
            "export",
            "import",
        ],
        "relevant_roles": [
            "kansainvälisen kaupan asiantuntija",
            "viennin edistäminen",
            "tuonnin hallinta",
            "markkinointi",
            "myynti",
            "asiakaspalvelu",
            "projektinhallinta",
            "liiketoimintasuunnittelu",
            "strateginen suunnittelu",
            "international trade specialist",
            "export promotion",
            "import management",
            "marketing",
            "sales",
            "customer service",
            "project management",
            "business planning",
            "strategic planning",
        ],
    },
    "tradenomi_liiketalous": {
        "name": "Tradenomi (AMK), liiketalous",
        "fields": ["Tradenomi (AMK), liiketalous"],
        "relevant_industries": [
            "liiketalous",
            "rahoitus",
            "konsultointi",
            "markkinointi",
            "myynti",
            "logistiikka",
            "hallinto",
            "business",
            "finance",
            "consulting",
            "marketing",
            "sales",
            "logistics",
            "administration",
        ],
        "relevant_roles": [
            "liiketalouden asiantuntija",
            "markkinointi",
            "myynti",
            "asiakaspalvelu",
            "projektinhallinta",
            "liiketoimintasuunnittelu",
            "taloushallinto",
            "business specialist",
            "marketing",
            "sales",
            "customer service",
            "project management",
            "business planning",
            "financial administration",
        ],
    },
    "tradenomi_liiketalous_verkkokoulutus": {
        "name": "Tradenomi (AMK), liiketalous, verkkokoulutus",
        "fields": ["Tradenomi (AMK), liiketalous, verkkokoulutus"],
        "relevant_industries": [
            "liiketalous",
            "rahoitus",
            "konsultointi",
            "markkinointi",
            "myynti",
            "logistiikka",
            "hallinto",
            "business",
            "finance",
            "consulting",
            "marketing",
            "sales",
            "logistics",
            "administration",
        ],
        "relevant_roles": [
            "liiketalouden asiantuntija",
            "markkinointi",
            "myynti",
            "asiakaspalvelu",
            "projektinhallinta",
            "liiketoimintasuunnittelu",
            "taloushallinto",
            "business specialist",
            "marketing",
            "sales",
            "customer service",
            "project management",
            "business planning",
            "financial administration",
        ],
    },
    # Culture Degrees
    "medianomi_amk": {
        "name": "Medianomi (AMK)",
        "fields": ["Medianomi (AMK)"],
        "relevant_industries": [
            "media",
            "viestintä",
            "viihde",
            "koulutus",
            "taide",
            "kulttuuri",
            "radio",
            "televisio",
            "julkaisu",
            "entertainment",
            "education",
            "arts",
            "broadcasting",
            "publishing",
        ],
        "relevant_roles": [
            "median tuotanto",
            "sisällön luonti",
            "opetus",
            "pedagogiikka",
            "kulttuurinhallinta",
            "taidehallinta",
            "luova suunnittelu",
            "multimedia suunnittelu",
            "äänituotanto",
            "kuvataide",
            "esittävät taiteet",
            "media production",
            "content creation",
            "teaching",
            "pedagogy",
            "cultural management",
            "arts administration",
            "creative direction",
            "multimedia design",
            "audio production",
            "visual arts",
            "performing arts",
        ],
    },
    "musiikkipedagogi_amk": {
        "name": "Musiikkipedagogi (AMK)",
        "fields": ["Musiikkipedagogi (AMK)"],
        "relevant_industries": [
            "media",
            "viestintä",
            "viihde",
            "koulutus",
            "taide",
            "kulttuuri",
            "radio",
            "televisio",
            "julkaisu",
            "entertainment",
            "education",
            "arts",
            "broadcasting",
            "publishing",
        ],
        "relevant_roles": [
            "musiikkikasvatus",
            "opetus",
            "pedagogiikka",
            "kulttuurinhallinta",
            "taidehallinta",
            "luova suunnittelu",
            "äänituotanto",
            "esittävät taiteet",
            "music education",
            "teaching",
            "pedagogy",
            "cultural management",
            "arts administration",
            "creative direction",
            "audio production",
            "performing arts",
        ],
    },
    "tanssinopettaja_amk": {
        "name": "Tanssinopettaja (AMK)",
        "fields": ["Tanssinopettaja (AMK)"],
        "relevant_industries": [
            "media",
            "viestintä",
            "viihde",
            "koulutus",
            "taide",
            "kulttuuri",
            "radio",
            "televisio",
            "julkaisu",
            "entertainment",
            "education",
            "arts",
            "broadcasting",
            "publishing",
        ],
        "relevant_roles": [
            "tanssinopetus",
            "opetus",
            "pedagogiikka",
            "kulttuurinhallinta",
            "taidehallinta",
            "luova suunnittelu",
            "koreografia",
            "esittävät taiteet",
            "dance teaching",
            "teaching",
            "pedagogy",
            "cultural management",
            "arts administration",
            "creative direction",
            "choreography",
            "performing arts",
        ],
    },
    # Natural Resources Degrees
    "agrologi_maaseutuelinkeinot": {
        "name": "Agrologi (AMK), maaseutuelinkeinot",
        "fields": ["Agrologi (AMK), maaseutuelinkeinot"],
        "relevant_industries": [
            "maatalous",
            "maaseutu",
            "ympäristö",
            "luonnonvarat",
            "elintarviketeollisuus",
            "kestävän kehityksen",
            "agriculture",
            "rural",
            "environmental",
            "natural resources",
            "food industry",
            "sustainable development",
        ],
        "relevant_roles": [
            "maatalousasiantuntija",
            "maaseudun kehitys",
            "ympäristösuunnittelu",
            "luonnonvarojen hallinta",
            "elintarviketurvallisuus",
            "kestävän kehityksen suunnittelu",
            "agricultural specialist",
            "rural development",
            "environmental planning",
            "natural resource management",
            "food safety",
            "sustainable development planning",
        ],
    },
    # Health Care Degrees
    "bachelor_of_health_care_nursing": {
        "name": "Bachelor of Health Care, Nursing",
        "fields": ["Bachelor of Health Care, Nursing"],
        "relevant_industries": [
            "terveydenhuolto",
            "lääketiede",
            "julkisterveys",
            "yhteisön terveys",
            "healthcare",
            "medical",
            "public health",
            "community health",
        ],
        "relevant_roles": [
            "sairaanhoitaja",
            "potilashoito",
            "terveyden edistäminen",
            "ehkäisevä hoito",
            "terveyskasvatus",
            "julkisterveyden palvelut",
            "terveyden arviointi",
            "nurse",
            "patient care",
            "health promotion",
            "preventive care",
            "health education",
            "public health services",
            "health assessment",
        ],
    },
    "bioanalyytikko_amk": {
        "name": "Bioanalyytikko (AMK)",
        "fields": ["Bioanalyytikko (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "lääketiede",
            "laboratorio",
            "tutkimus",
            "diagnostiikka",
            "healthcare",
            "medical",
            "laboratory",
            "research",
            "diagnostics",
        ],
        "relevant_roles": [
            "bioanalyytikko",
            "laboratoriotyö",
            "lääketieteellinen testaus",
            "näytteiden analysointi",
            "diagnostinen testaus",
            "laadunvalvonta",
            "tutkimustuki",
            "laboratorion hallinta",
            "biomedical laboratory scientist",
            "laboratory work",
            "medical testing",
            "sample analysis",
            "diagnostic testing",
            "quality control",
            "research support",
            "laboratory management",
        ],
    },
    "ensihoitaja_amk": {
        "name": "Ensihoitaja (AMK)",
        "fields": ["Ensihoitaja (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "lääketiede",
            "ensihoito",
            "hälytyskeskus",
            "healthcare",
            "medical",
            "emergency care",
            "emergency center",
        ],
        "relevant_roles": [
            "ensihoitaja",
            "ensihoitopalvelut",
            "hälytyskeskus",
            "ensihoitokoulutus",
            "emergency care nurse",
            "emergency care services",
            "emergency center",
            "emergency care training",
        ],
    },
    "fysioterapeutti_amk": {
        "name": "Fysioterapeutti (AMK)",
        "fields": ["Fysioterapeutti (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "lääketiede",
            "kuntoutus",
            "hyvinvointi",
            "urheilu",
            "kuntoilu",
            "healthcare",
            "medical",
            "rehabilitation",
            "wellness",
            "sports",
            "fitness",
        ],
        "relevant_roles": [
            "fysioterapia",
            "kuntoutus",
            "potilashoito",
            "terveyden arviointi",
            "hoidon suunnittelu",
            "liikuntaterapia",
            "manuaaliterapia",
            "urheiluterapia",
            "hyvinvointivalmennus",
            "physiotherapy",
            "physical therapy",
            "rehabilitation",
            "patient care",
            "health assessment",
            "treatment planning",
            "exercise therapy",
            "manual therapy",
            "sports therapy",
            "wellness coaching",
        ],
    },
    "katilo_amk": {
        "name": "Kätilö (AMK)",
        "fields": ["Kätilö (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "lääketiede",
            "synnytys",
            "naistentauti",
            "healthcare",
            "medical",
            "maternity",
            "gynecology",
        ],
        "relevant_roles": [
            "kätilö",
            "synnytyshoito",
            "naistentauti",
            "perhekeskus",
            "synnytysvalmennus",
            "midwife",
            "maternity care",
            "gynecology",
            "family center",
            "birth preparation",
        ],
    },
    "hammashoitaja_amk": {
        "name": "Hammashoitaja (AMK)",
        "fields": ["Hammashoitaja (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "hammaslääketiede",
            "lääketiede",
            "suun terveys",
            "healthcare",
            "dental",
            "medical",
            "oral health",
        ],
        "relevant_roles": [
            "hammashygienia",
            "suun terveydenhoito",
            "hammashoito",
            "potilaskasvatus",
            "ehkäisevä hoito",
            "hammashoidon toimenpiteet",
            "suuhygienian ohjeistus",
            "dental hygiene",
            "oral health care",
            "dental care",
            "patient education",
            "preventive care",
            "dental treatment",
            "oral hygiene instruction",
        ],
    },
    "kuntoutuksen_ohjaaja_amk": {
        "name": "Kuntoutuksen ohjaaja (AMK)",
        "fields": ["Kuntoutuksen ohjaaja (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "kuntoutus",
            "hyvinvointi",
            "urheilu",
            "kuntoilu",
            "healthcare",
            "rehabilitation",
            "wellness",
            "sports",
            "fitness",
        ],
        "relevant_roles": [
            "kuntoutuksen ohjaus",
            "liikunnan ohjaus",
            "hyvinvointivalmennus",
            "terveyden edistäminen",
            "kuntoutussuunnittelu",
            "potilasohjaus",
            "kuntovalmentaminen",
            "rehabilitation guidance",
            "exercise guidance",
            "wellness coaching",
            "health promotion",
            "rehabilitation planning",
            "patient guidance",
            "fitness training",
        ],
    },
    "laboratoriohoitaja_amk": {
        "name": "Laboratoriohoitaja (AMK)",
        "fields": ["Laboratoriohoitaja (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "lääketiede",
            "laboratorio",
            "tutkimus",
            "diagnostiikka",
            "healthcare",
            "medical",
            "laboratory",
            "research",
            "diagnostics",
        ],
        "relevant_roles": [
            "laboratoriotyö",
            "lääketieteellinen testaus",
            "näytteiden analysointi",
            "diagnostinen testaus",
            "laadunvalvonta",
            "tutkimustuki",
            "laboratorion hallinta",
            "laboratory work",
            "medical testing",
            "sample analysis",
            "diagnostic testing",
            "quality control",
            "research support",
            "laboratory management",
        ],
    },
    "optometristi_amk": {
        "name": "Optometristi (AMK)",
        "fields": ["Optometristi (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "optiikka",
            "näönhoito",
            "lääketiede",
            "healthcare",
            "optical",
            "vision care",
            "medical",
        ],
        "relevant_roles": [
            "näönhoito",
            "silmäntarkastus",
            "optiset palvelut",
            "näön korjaus",
            "piilolinssien sovitus",
            "näön terapia",
            "silmän terveyden arviointi",
            "vision care",
            "eye examination",
            "optical services",
            "vision correction",
            "contact lens fitting",
            "vision therapy",
            "eye health assessment",
        ],
    },
    "rontgenhoitaja_amk": {
        "name": "Röntgenhoitaja (AMK)",
        "fields": ["Röntgenhoitaja (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "lääketiede",
            "radiologia",
            "diagnostiikka",
            "healthcare",
            "medical",
            "radiology",
            "diagnostics",
        ],
        "relevant_roles": [
            "rontgenhoitaja",
            "radiologinen tutkimus",
            "kuvantamistekniikka",
            "diagnostinen kuvaus",
            "laadunvalvonta",
            "radiologic nurse",
            "radiologic examination",
            "imaging technology",
            "diagnostic imaging",
            "quality control",
        ],
    },
    "sairaanhoitaja_amk": {
        "name": "Sairaanhoitaja (AMK)",
        "fields": ["Sairaanhoitaja (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "lääketiede",
            "julkisterveys",
            "yhteisön terveys",
            "healthcare",
            "medical",
            "public health",
            "community health",
        ],
        "relevant_roles": [
            "sairaanhoitaja",
            "potilashoito",
            "terveyden edistäminen",
            "ehkäisevä hoito",
            "terveyskasvatus",
            "julkisterveyden palvelut",
            "terveyden arviointi",
            "nurse",
            "patient care",
            "health promotion",
            "preventive care",
            "health education",
            "public health services",
            "health assessment",
        ],
    },
    "sosionomi_amk": {
        "name": "Sosionomi (AMK)",
        "fields": ["Sosionomi (AMK)"],
        "relevant_industries": [
            "sosiaalipalvelut",
            "terveydenhuolto",
            "julkishallinto",
            "koulutus",
            "social services",
            "healthcare",
            "public administration",
            "education",
        ],
        "relevant_roles": [
            "sosionomi",
            "sosiaalityö",
            "sosiaalipalvelut",
            "perhetyö",
            "lastensuojelu",
            "vanhustyö",
            "social worker",
            "social work",
            "social services",
            "family work",
            "child protection",
            "elderly care",
        ],
    },
    "suuhygienisti_amk": {
        "name": "Suuhygienisti (AMK)",
        "fields": ["Suuhygienisti (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "hammaslääketiede",
            "lääketiede",
            "suun terveys",
            "healthcare",
            "dental",
            "medical",
            "oral health",
        ],
        "relevant_roles": [
            "suuhygienisti",
            "suun terveydenhoito",
            "hammashoito",
            "potilaskasvatus",
            "ehkäisevä hoito",
            "hammashoidon toimenpiteet",
            "suuhygienian ohjeistus",
            "dental hygienist",
            "oral health care",
            "dental care",
            "patient education",
            "preventive care",
            "dental treatment",
            "oral hygiene instruction",
        ],
    },
    "toimintaterapeutti_amk": {
        "name": "Toimintaterapeutti (AMK)",
        "fields": ["Toimintaterapeutti (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "lääketiede",
            "kuntoutus",
            "hyvinvointi",
            "healthcare",
            "medical",
            "rehabilitation",
            "wellness",
        ],
        "relevant_roles": [
            "toimintaterapeutti",
            "kuntoutus",
            "potilashoito",
            "terveyden arviointi",
            "hoidon suunnittelu",
            "toimintaterapia",
            "occupational therapist",
            "rehabilitation",
            "patient care",
            "health assessment",
            "treatment planning",
            "occupational therapy",
        ],
    },
    "sosiaali_ja_terveysalan_johtaja_amk": {
        "name": "Sosiaali- ja terveysalan johtaja (AMK)",
        "fields": ["Sosiaali- ja terveysalan johtaja (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "sosiaalipalvelut",
            "lääketiede",
            "julkisterveys",
            "healthcare",
            "social services",
            "medical",
            "public health",
        ],
        "relevant_roles": [
            "terveydenhuollon johtaminen",
            "sosiaalipalvelujen johtaminen",
            "terveydenhuollon hallinto",
            "julkisterveyden johtaminen",
            "terveydenhuollon johtajuus",
            "sosiaalityön johtaminen",
            "terveydenhuollon suunnittelu",
            "healthcare management",
            "social services management",
            "healthcare administration",
            "public health management",
            "healthcare leadership",
            "social work management",
            "healthcare planning",
        ],
    },
    "terveydenhoitaja_amk": {
        "name": "Terveydenhoitaja (AMK)",
        "fields": ["Terveydenhoitaja (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "julkisterveys",
            "lääketiede",
            "yhteisön terveys",
            "healthcare",
            "public health",
            "medical",
            "community health",
        ],
        "relevant_roles": [
            "julkisterveyden hoitotyö",
            "yhteisön terveys",
            "terveyden edistäminen",
            "ehkäisevä hoito",
            "terveyskasvatus",
            "julkisterveyden palvelut",
            "terveyden arviointi",
            "public health nursing",
            "community health",
            "health promotion",
            "preventive care",
            "health education",
            "public health services",
            "health assessment",
        ],
    },
    # Engineering Degrees
    "bachelor_of_engineering_energy_and_environmental_engineering": {
        "name": "Bachelor of Engineering, Energy and Environmental Engineering",
        "fields": ["Bachelor of Engineering, Energy and Environmental Engineering"],
        "relevant_industries": [
            "valmistus",
            "rakennus",
            "teknologia",
            "energia",
            "ympäristö",
            "kestävän kehityksen",
            "manufacturing",
            "construction",
            "technology",
            "energy",
            "environmental",
            "sustainable development",
        ],
        "relevant_roles": [
            "suunnittelu",
            "kehitys",
            "testaus",
            "huolto",
            "projektinhallinta",
            "tutkimus",
            "laadunvalvonta",
            "tekniikkatuki",
            "järjestelmänhallinta",
            "energiatekniikka",
            "ympäristötekniikka",
            "kestävän kehityksen suunnittelu",
            "energiatehokkuus",
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "energy technology",
            "environmental technology",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "bachelor_of_engineering_mechanical_engineering": {
        "name": "Bachelor of Engineering, Mechanical Engineering",
        "fields": ["Bachelor of Engineering, Mechanical Engineering"],
        "relevant_industries": [
            "valmistus",
            "rakennus",
            "teknologia",
            "autoteollisuus",
            "ilmailu",
            "energia",
            "ympäristö",
            "rakennuspalvelut",
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "suunnittelu",
            "kehitys",
            "testaus",
            "huolto",
            "projektinhallinta",
            "tutkimus",
            "laadunvalvonta",
            "tekniikkatuki",
            "järjestelmänhallinta",
            "konetekniikka",
            "automaatio",
            "rakennustekniikka",
            "rakennushallinta",
            "kestävän kehityksen suunnittelu",
            "energiatehokkuus",
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "mechanical engineering",
            "automation",
            "building technology",
            "construction management",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "insinoori_energia_ja_ymparistotekniikka": {
        "name": "Insinööri (AMK), energia- ja ympäristötekniikka",
        "fields": ["Insinööri (AMK), energia- ja ympäristötekniikka"],
        "relevant_industries": [
            "valmistus",
            "rakennus",
            "teknologia",
            "energia",
            "ympäristö",
            "kestävän kehityksen",
            "manufacturing",
            "construction",
            "technology",
            "energy",
            "environmental",
            "sustainable development",
        ],
        "relevant_roles": [
            "suunnittelu",
            "kehitys",
            "testaus",
            "huolto",
            "projektinhallinta",
            "tutkimus",
            "laadunvalvonta",
            "tekniikkatuki",
            "järjestelmänhallinta",
            "energiatekniikka",
            "ympäristötekniikka",
            "kestävän kehityksen suunnittelu",
            "energiatehokkuus",
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "energy technology",
            "environmental technology",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "insinoori_amk_konetekniikka": {
        "name": "Insinööri (AMK), konetekniikka",
        "fields": ["Insinööri (AMK), konetekniikka"],
        "relevant_industries": [
            "valmistus",
            "rakennus",
            "teknologia",
            "autoteollisuus",
            "ilmailu",
            "energia",
            "ympäristö",
            "rakennuspalvelut",
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "suunnittelu",
            "kehitys",
            "testaus",
            "huolto",
            "projektinhallinta",
            "tutkimus",
            "laadunvalvonta",
            "tekniikkatuki",
            "järjestelmänhallinta",
            "konetekniikka",
            "automaatio",
            "rakennustekniikka",
            "rakennushallinta",
            "kestävän kehityksen suunnittelu",
            "energiatehokkuus",
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "mechanical engineering",
            "automation",
            "building technology",
            "construction management",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "insinoori_amk_sahko_ja_automaatiotekniikka": {
        "name": "Insinööri (AMK), sähkö- ja automaatiotekniikka",
        "fields": ["Insinööri (AMK), sähkö- ja automaatiotekniikka"],
        "relevant_industries": [
            "valmistus",
            "rakennus",
            "teknologia",
            "autoteollisuus",
            "ilmailu",
            "energia",
            "ympäristö",
            "rakennuspalvelut",
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "suunnittelu",
            "kehitys",
            "testaus",
            "huolto",
            "projektinhallinta",
            "tutkimus",
            "laadunvalvonta",
            "tekniikkatuki",
            "järjestelmänhallinta",
            "sähkötekniikka",
            "automaatio",
            "rakennustekniikka",
            "rakennushallinta",
            "kestävän kehityksen suunnittelu",
            "energiatehokkuus",
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "electrical engineering",
            "automation",
            "building technology",
            "construction management",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "insinoori_amk_talotekniikka": {
        "name": "Insinööri (AMK), talotekniikka",
        "fields": ["Insinööri (AMK), talotekniikka"],
        "relevant_industries": [
            "valmistus",
            "rakennus",
            "teknologia",
            "autoteollisuus",
            "ilmailu",
            "energia",
            "ympäristö",
            "rakennuspalvelut",
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "suunnittelu",
            "kehitys",
            "testaus",
            "huolto",
            "projektinhallinta",
            "tutkimus",
            "laadunvalvonta",
            "tekniikkatuki",
            "järjestelmänhallinta",
            "rakennustekniikka",
            "rakennushallinta",
            "arkkitehtuuri",
            "kestävän kehityksen suunnittelu",
            "energiatehokkuus",
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "building technology",
            "construction management",
            "architecture",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "insinoori_amk_rakennus_ja_yhdyskuntatekniikka": {
        "name": "Insinööri (AMK), rakennus- ja yhdyskuntatekniikka",
        "fields": ["Insinööri (AMK), rakennus- ja yhdyskuntatekniikka"],
        "relevant_industries": [
            "valmistus",
            "rakennus",
            "teknologia",
            "autoteollisuus",
            "ilmailu",
            "energia",
            "ympäristö",
            "rakennuspalvelut",
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "suunnittelu",
            "kehitys",
            "testaus",
            "huolto",
            "projektinhallinta",
            "tutkimus",
            "laadunvalvonta",
            "tekniikkatuki",
            "järjestelmänhallinta",
            "rakennustekniikka",
            "rakennushallinta",
            "arkkitehtuuri",
            "kestävän kehityksen suunnittelu",
            "energiatehokkuus",
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "building technology",
            "construction management",
            "architecture",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "rakennusarkkitehti_amk": {
        "name": "Rakennusarkkitehti (AMK)",
        "fields": ["Rakennusarkkitehti (AMK)"],
        "relevant_industries": [
            "valmistus",
            "rakennus",
            "teknologia",
            "autoteollisuus",
            "ilmailu",
            "energia",
            "ympäristö",
            "rakennuspalvelut",
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "suunnittelu",
            "kehitys",
            "testaus",
            "huolto",
            "projektinhallinta",
            "tutkimus",
            "laadunvalvonta",
            "tekniikkatuki",
            "järjestelmänhallinta",
            "rakennustekniikka",
            "rakennushallinta",
            "arkkitehtuuri",
            "kestävän kehityksen suunnittelu",
            "energiatehokkuus",
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "building technology",
            "construction management",
            "architecture",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "rakennusmestari_amk": {
        "name": "Rakennusmestari (AMK)",
        "fields": ["Rakennusmestari (AMK)"],
        "relevant_industries": [
            "valmistus",
            "rakennus",
            "teknologia",
            "autoteollisuus",
            "ilmailu",
            "energia",
            "ympäristö",
            "rakennuspalvelut",
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "suunnittelu",
            "kehitys",
            "testaus",
            "huolto",
            "projektinhallinta",
            "tutkimus",
            "laadunvalvonta",
            "tekniikkatuki",
            "järjestelmänhallinta",
            "rakennustekniikka",
            "rakennushallinta",
            "arkkitehtuuri",
            "kestävän kehityksen suunnittelu",
            "energiatehokkuus",
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "building technology",
            "construction management",
            "architecture",
            "sustainable design",
            "energy efficiency",
        ],
    },
    # General Studies (fallback)
    "general": {
        "name": "General Studies",
        "fields": [
            "Liberal Arts",
            "General Studies",
            "Interdisciplinary Studies",
        ],
        "relevant_industries": ["any"],
        "relevant_roles": ["any"],
    },
}
