"""
Finnish degree programs data for the LLM evaluation system.
This file contains all the specific degree programs with their relevant industries and roles in Finnish.
"""

DEGREE_PROGRAMS_FI = {
    # Information Technology Degrees
    "bachelor_of_engineering_information_technology": {
        "name": "Bachelor of Engineering (BEng), Information Technology",
        "fields": ["Bachelor of Engineering (BEng), Information Technology"],
        "relevant_industries": [
            "teknologia",
            "ohjelmisto",
            "konsultointi",
            "rahoitus",
            "terveydenhuolto",
            "koulutus",
            "tietoliikenne",
            "tietotekniikka",
            "tietojärjestelmät",
            "tietoturva",
            "tietohallinto",
            "IT",
            "information technology",
            "software",
            "consulting",
            "finance",
            "healthcare",
            "education",
            "telecommunications",
            "information systems",
            "information security",
            "information management",
        ],
        "relevant_roles": [
            "ohjelmistokehitys",
            "ohjelmistokehittäjä",
            "ohjelmointi",
            "web-kehitys",
            "mobiilikehitys",
            "sovelluskehitys",
            "järjestelmänhallinta",
            "tietokantojen hallinta",
            "verkkohallinta",
            "tietoturva",
            "tietojen analysointi",
            "tietotuki",
            "tekniikkatuki",
            "tietojenkäsittely",
            "digitaalinen muutos",
            "pilvipalvelut",
            "tekoäly",
            "koneoppiminen",
            "tietoarkkitehtuuri",
            "tietojen visualisointi",
            "kehittäjä",
            "ohjelmoija",
            "järjestelmäasiantuntija",
            "tietokanta-asiantuntija",
            "verkkoasiantuntija",
            "tietoturva-asiantuntija",
            "tietoanalyytikko",
            "tietojärjestelmäasiantuntija",
            "software development",
            "software engineering",
            "web development",
            "mobile development",
            "full stack development",
            "front end development",
            "back end development",
            "mobile app development",
            "web app development",
            "programming",
            "system administration",
            "database management",
            "network administration",
            "cybersecurity",
            "data analysis",
            "IT support",
            "technical support",
            "data science",
            "information systems",
            "digital transformation",
            "cloud computing",
            "AI",
            "machine learning",
            "data engineering",
            "data visualization",
            "data architecture",
            "data security",
            "data governance",
        ],
    },
    "insinoori_tieto_ja_viestintatekniikka": {
        "name": "Insinööri (AMK), tieto- ja viestintätekniikka",
        "fields": ["Insinööri (AMK), tieto- ja viestintätekniikka"],
        "relevant_industries": [
            "teknologia",
            "ohjelmisto",
            "konsultointi",
            "rahoitus",
            "terveydenhuolto",
            "koulutus",
            "tietoliikenne",
            "tietotekniikka",
            "tietojärjestelmät",
            "tietoturva",
            "tietohallinto",
            "IT",
            "information technology",
            "software",
            "consulting",
            "finance",
            "healthcare",
            "education",
            "telecommunications",
            "information systems",
            "information security",
            "information management",
        ],
        "relevant_roles": [
            "ohjelmistokehitys",
            "ohjelmistokehittäjä",
            "ohjelmointi",
            "web-kehitys",
            "mobiilikehitys",
            "sovelluskehitys",
            "järjestelmänhallinta",
            "tietokantojen hallinta",
            "verkkohallinta",
            "tietoturva",
            "tietojen analysointi",
            "tietotuki",
            "tekniikkatuki",
            "tietojenkäsittely",
            "digitaalinen muutos",
            "pilvipalvelut",
            "tekoäly",
            "koneoppiminen",
            "tietoarkkitehtuuri",
            "tietojen visualisointi",
            "kehittäjä",
            "ohjelmoija",
            "järjestelmäasiantuntija",
            "tietokanta-asiantuntija",
            "verkkoasiantuntija",
            "tietoturva-asiantuntija",
            "tietoanalyytikko",
            "tietojärjestelmäasiantuntija",
            "software development",
            "software engineering",
            "web development",
            "mobile development",
            "full stack development",
            "front end development",
            "back end development",
            "mobile app development",
            "web app development",
            "programming",
            "system administration",
            "database management",
            "network administration",
            "cybersecurity",
            "data analysis",
            "IT support",
            "technical support",
            "data science",
            "information systems",
            "digital transformation",
            "cloud computing",
            "AI",
            "machine learning",
            "data engineering",
            "data visualization",
            "data architecture",
            "data security",
            "data governance",
        ],
    },
    "tradenomi_tietojenkasittely": {
        "name": "Tradenomi (AMK), tietojenkäsittely",
        "fields": ["Tradenomi (AMK), tietojenkäsittely"],
        "relevant_industries": [
            "teknologia",
            "ohjelmisto",
            "konsultointi",
            "rahoitus",
            "terveydenhuolto",
            "koulutus",
            "tietoliikenne",
            "tietotekniikka",
            "tietojärjestelmät",
            "tietoturva",
            "tietohallinto",
            "IT",
            "information technology",
            "software",
            "consulting",
            "finance",
            "healthcare",
            "education",
            "telecommunications",
            "information systems",
            "information security",
            "information management",
        ],
        "relevant_roles": [
            "ohjelmistokehitys",
            "ohjelmistokehittäjä",
            "ohjelmointi",
            "web-kehitys",
            "mobiilikehitys",
            "sovelluskehitys",
            "järjestelmänhallinta",
            "tietokantojen hallinta",
            "verkkohallinta",
            "tietoturva",
            "tietojen analysointi",
            "tietotuki",
            "tekniikkatuki",
            "tietojenkäsittely",
            "digitaalinen muutos",
            "pilvipalvelut",
            "tekoäly",
            "koneoppiminen",
            "tietoarkkitehtuuri",
            "tietojen visualisointi",
            "kehittäjä",
            "ohjelmoija",
            "järjestelmäasiantuntija",
            "tietokanta-asiantuntija",
            "verkkoasiantuntija",
            "tietoturva-asiantuntija",
            "tietoanalyytikko",
            "tietojärjestelmäasiantuntija",
            "software development",
            "software engineering",
            "web development",
            "mobile development",
            "full stack development",
            "front end development",
            "back end development",
            "mobile app development",
            "web app development",
            "programming",
            "system administration",
            "database management",
            "network administration",
            "cybersecurity",
            "data analysis",
            "IT support",
            "technical support",
            "data science",
            "information systems",
            "digital transformation",
            "cloud computing",
            "AI",
            "machine learning",
            "data engineering",
            "data visualization",
            "data architecture",
            "data security",
            "data governance",
        ],
    },
    # Culture Degrees
    "medianomi_amk": {
        "name": "Medianomi (AMK)",
        "fields": ["Medianomi (AMK)"],
        "relevant_industries": [
            "media",
            "viestintä",
            "viihde",
            "koulutus",
            "taide",
            "kulttuuri",
            "radio",
            "televisio",
            "julkaisu",
            "entertainment",
            "education",
            "arts",
            "broadcasting",
            "publishing",
        ],
        "relevant_roles": [
            "median tuotanto",
            "sisällön luonti",
            "opetus",
            "pedagogiikka",
            "kulttuurinhallinta",
            "taidehallinta",
            "luova suunnittelu",
            "multimedia suunnittelu",
            "äänituotanto",
            "kuvataide",
            "esittävät taiteet",
            "media production",
            "content creation",
            "teaching",
            "pedagogy",
            "cultural management",
            "arts administration",
            "creative direction",
            "multimedia design",
            "audio production",
            "visual arts",
            "performing arts",
        ],
    },
    "musiikkipedagogi_amk": {
        "name": "Musiikkipedagogi (AMK)",
        "fields": ["Musiikkipedagogi (AMK)"],
        "relevant_industries": [
            "media",
            "viestintä",
            "viihde",
            "koulutus",
            "taide",
            "kulttuuri",
            "radio",
            "televisio",
            "julkaisu",
            "entertainment",
            "education",
            "arts",
            "broadcasting",
            "publishing",
        ],
        "relevant_roles": [
            "musiikkikasvatus",
            "opetus",
            "pedagogiikka",
            "kulttuurinhallinta",
            "taidehallinta",
            "luova suunnittelu",
            "äänituotanto",
            "esittävät taiteet",
            "music education",
            "teaching",
            "pedagogy",
            "cultural management",
            "arts administration",
            "creative direction",
            "audio production",
            "performing arts",
        ],
    },
    # Health Care Degrees
    "fysioterapeutti_amk": {
        "name": "Fysioterapeutti (AMK)",
        "fields": ["Fysioterapeutti (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "lääketiede",
            "kuntoutus",
            "hyvinvointi",
            "urheilu",
            "kuntoilu",
            "healthcare",
            "medical",
            "rehabilitation",
            "wellness",
            "sports",
            "fitness",
        ],
        "relevant_roles": [
            "fysioterapia",
            "kuntoutus",
            "potilashoito",
            "terveyden arviointi",
            "hoidon suunnittelu",
            "liikuntaterapia",
            "manuaaliterapia",
            "urheiluterapia",
            "hyvinvointivalmennus",
            "physiotherapy",
            "physical therapy",
            "rehabilitation",
            "patient care",
            "health assessment",
            "treatment planning",
            "exercise therapy",
            "manual therapy",
            "sports therapy",
            "wellness coaching",
        ],
    },
    "hammashoitaja_amk": {
        "name": "Hammashoitaja (AMK)",
        "fields": ["Hammashoitaja (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "hammaslääketiede",
            "lääketiede",
            "suun terveys",
            "healthcare",
            "dental",
            "medical",
            "oral health",
        ],
        "relevant_roles": [
            "hammashygienia",
            "suun terveydenhoito",
            "hammashoito",
            "potilaskasvatus",
            "ehkäisevä hoito",
            "hammashoidon toimenpiteet",
            "suuhygienian ohjeistus",
            "dental hygiene",
            "oral health care",
            "dental care",
            "patient education",
            "preventive care",
            "dental treatment",
            "oral hygiene instruction",
        ],
    },
    "kuntoutuksen_ohjaaja_amk": {
        "name": "Kuntoutuksen ohjaaja (AMK)",
        "fields": ["Kuntoutuksen ohjaaja (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "kuntoutus",
            "hyvinvointi",
            "urheilu",
            "kuntoilu",
            "healthcare",
            "rehabilitation",
            "wellness",
            "sports",
            "fitness",
        ],
        "relevant_roles": [
            "kuntoutuksen ohjaus",
            "liikunnan ohjaus",
            "hyvinvointivalmennus",
            "terveyden edistäminen",
            "kuntoutussuunnittelu",
            "potilasohjaus",
            "kuntovalmentaminen",
            "rehabilitation guidance",
            "exercise guidance",
            "wellness coaching",
            "health promotion",
            "rehabilitation planning",
            "patient guidance",
            "fitness training",
        ],
    },
    "laboratoriohoitaja_amk": {
        "name": "Laboratoriohoitaja (AMK)",
        "fields": ["Laboratoriohoitaja (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "lääketiede",
            "laboratorio",
            "tutkimus",
            "diagnostiikka",
            "healthcare",
            "medical",
            "laboratory",
            "research",
            "diagnostics",
        ],
        "relevant_roles": [
            "laboratoriotyö",
            "lääketieteellinen testaus",
            "näytteiden analysointi",
            "diagnostinen testaus",
            "laadunvalvonta",
            "tutkimustuki",
            "laboratorion hallinta",
            "laboratory work",
            "medical testing",
            "sample analysis",
            "diagnostic testing",
            "quality control",
            "research support",
            "laboratory management",
        ],
    },
    "optometristi_amk": {
        "name": "Optometristi (AMK)",
        "fields": ["Optometristi (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "optiikka",
            "näönhoito",
            "lääketiede",
            "healthcare",
            "optical",
            "vision care",
            "medical",
        ],
        "relevant_roles": [
            "näönhoito",
            "silmäntarkastus",
            "optiset palvelut",
            "näön korjaus",
            "piilolinssien sovitus",
            "näön terapia",
            "silmän terveyden arviointi",
            "vision care",
            "eye examination",
            "optical services",
            "vision correction",
            "contact lens fitting",
            "vision therapy",
            "eye health assessment",
        ],
    },
    "sosiaali_ja_terveysalan_johtaja_amk": {
        "name": "Sosiaali- ja terveysalan johtaja (AMK)",
        "fields": ["Sosiaali- ja terveysalan johtaja (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "sosiaalipalvelut",
            "lääketiede",
            "julkisterveys",
            "healthcare",
            "social services",
            "medical",
            "public health",
        ],
        "relevant_roles": [
            "terveydenhuollon johtaminen",
            "sosiaalipalvelujen johtaminen",
            "terveydenhuollon hallinto",
            "julkisterveyden johtaminen",
            "terveydenhuollon johtajuus",
            "sosiaalityön johtaminen",
            "terveydenhuollon suunnittelu",
            "healthcare management",
            "social services management",
            "healthcare administration",
            "public health management",
            "healthcare leadership",
            "social work management",
            "healthcare planning",
        ],
    },
    "terveydenhoitaja_amk": {
        "name": "Terveydenhoitaja (AMK)",
        "fields": ["Terveydenhoitaja (AMK)"],
        "relevant_industries": [
            "terveydenhuolto",
            "julkisterveys",
            "lääketiede",
            "yhteisön terveys",
            "healthcare",
            "public health",
            "medical",
            "community health",
        ],
        "relevant_roles": [
            "julkisterveyden hoitotyö",
            "yhteisön terveys",
            "terveyden edistäminen",
            "ehkäisevä hoito",
            "terveyskasvatus",
            "julkisterveyden palvelut",
            "terveyden arviointi",
            "public health nursing",
            "community health",
            "health promotion",
            "preventive care",
            "health education",
            "public health services",
            "health assessment",
        ],
    },
    # Engineering Degrees
    "insinoori_amk_konetekniikka": {
        "name": "Insinööri (AMK), konetekniikka",
        "fields": ["Insinööri (AMK), konetekniikka"],
        "relevant_industries": [
            "valmistus",
            "rakennus",
            "teknologia",
            "autoteollisuus",
            "ilmailu",
            "energia",
            "ympäristö",
            "rakennuspalvelut",
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "suunnittelu",
            "kehitys",
            "testaus",
            "huolto",
            "projektinhallinta",
            "tutkimus",
            "laadunvalvonta",
            "tekniikkatuki",
            "järjestelmänhallinta",
            "konetekniikka",
            "automaatio",
            "rakennustekniikka",
            "rakennushallinta",
            "kestävän kehityksen suunnittelu",
            "energiatehokkuus",
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "mechanical engineering",
            "automation",
            "building technology",
            "construction management",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "insinoori_amk_sahko_ja_automaatiotekniikka": {
        "name": "Insinööri (AMK), sähkö- ja automaatiotekniikka",
        "fields": ["Insinööri (AMK), sähkö- ja automaatiotekniikka"],
        "relevant_industries": [
            "valmistus",
            "rakennus",
            "teknologia",
            "autoteollisuus",
            "ilmailu",
            "energia",
            "ympäristö",
            "rakennuspalvelut",
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "suunnittelu",
            "kehitys",
            "testaus",
            "huolto",
            "projektinhallinta",
            "tutkimus",
            "laadunvalvonta",
            "tekniikkatuki",
            "järjestelmänhallinta",
            "sähkötekniikka",
            "automaatio",
            "rakennustekniikka",
            "rakennushallinta",
            "kestävän kehityksen suunnittelu",
            "energiatehokkuus",
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "electrical engineering",
            "automation",
            "building technology",
            "construction management",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "insinoori_amk_talotekniikka": {
        "name": "Insinööri (AMK), talotekniikka",
        "fields": ["Insinööri (AMK), talotekniikka"],
        "relevant_industries": [
            "valmistus",
            "rakennus",
            "teknologia",
            "autoteollisuus",
            "ilmailu",
            "energia",
            "ympäristö",
            "rakennuspalvelut",
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "suunnittelu",
            "kehitys",
            "testaus",
            "huolto",
            "projektinhallinta",
            "tutkimus",
            "laadunvalvonta",
            "tekniikkatuki",
            "järjestelmänhallinta",
            "rakennustekniikka",
            "rakennushallinta",
            "arkkitehtuuri",
            "kestävän kehityksen suunnittelu",
            "energiatehokkuus",
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "building technology",
            "construction management",
            "architecture",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "insinoori_amk_rakennus_ja_yhdyskuntatekniikka": {
        "name": "Insinööri (AMK), rakennus- ja yhdyskuntatekniikka",
        "fields": ["Insinööri (AMK), rakennus- ja yhdyskuntatekniikka"],
        "relevant_industries": [
            "valmistus",
            "rakennus",
            "teknologia",
            "autoteollisuus",
            "ilmailu",
            "energia",
            "ympäristö",
            "rakennuspalvelut",
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "suunnittelu",
            "kehitys",
            "testaus",
            "huolto",
            "projektinhallinta",
            "tutkimus",
            "laadunvalvonta",
            "tekniikkatuki",
            "järjestelmänhallinta",
            "rakennustekniikka",
            "rakennushallinta",
            "arkkitehtuuri",
            "kestävän kehityksen suunnittelu",
            "energiatehokkuus",
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "building technology",
            "construction management",
            "architecture",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "rakennusarkkitehti_amk": {
        "name": "Rakennusarkkitehti (AMK)",
        "fields": ["Rakennusarkkitehti (AMK)"],
        "relevant_industries": [
            "valmistus",
            "rakennus",
            "teknologia",
            "autoteollisuus",
            "ilmailu",
            "energia",
            "ympäristö",
            "rakennuspalvelut",
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "suunnittelu",
            "kehitys",
            "testaus",
            "huolto",
            "projektinhallinta",
            "tutkimus",
            "laadunvalvonta",
            "tekniikkatuki",
            "järjestelmänhallinta",
            "rakennustekniikka",
            "rakennushallinta",
            "arkkitehtuuri",
            "kestävän kehityksen suunnittelu",
            "energiatehokkuus",
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "building technology",
            "construction management",
            "architecture",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "rakennusmestari_amk": {
        "name": "Rakennusmestari (AMK)",
        "fields": ["Rakennusmestari (AMK)"],
        "relevant_industries": [
            "valmistus",
            "rakennus",
            "teknologia",
            "autoteollisuus",
            "ilmailu",
            "energia",
            "ympäristö",
            "rakennuspalvelut",
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "suunnittelu",
            "kehitys",
            "testaus",
            "huolto",
            "projektinhallinta",
            "tutkimus",
            "laadunvalvonta",
            "tekniikkatuki",
            "järjestelmänhallinta",
            "rakennustekniikka",
            "rakennushallinta",
            "arkkitehtuuri",
            "kestävän kehityksen suunnittelu",
            "energiatehokkuus",
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "building technology",
            "construction management",
            "architecture",
            "sustainable design",
            "energy efficiency",
        ],
    },
    # General Studies (fallback)
    "general": {
        "name": "General Studies",
        "fields": [
            "Liberal Arts",
            "General Studies",
            "Interdisciplinary Studies",
        ],
        "relevant_industries": ["any"],
        "relevant_roles": ["any"],
    },
}
