"""
Degree programs data for the LLM evaluation system.
This file contains all the specific degree programs with their relevant industries and roles.
"""

DEGREE_PROGRAMS = {
    # Information Technology Degrees
    "bachelor_of_engineering_information_technology": {
        "name": "Bachelor of Engineering (BEng), Information Technology",
        "fields": ["Bachelor of Engineering (BEng), Information Technology"],
        "relevant_industries": [
            "technology",
            "software",
            "consulting",
            "finance",
            "healthcare",
            "education",
            "telecommunications",
            "IT",
            "information technology",
            "information systems",
            "information security",
            "information management",
        ],
        "relevant_roles": [
            "software development",
            "software engineering",
            "web development",
            "mobile development",
            "full stack development",
            "front end development",
            "back end development",
            "mobile app development",
            "web app development",
            "programming",
            "system administration",
            "database management",
            "network administration",
            "cybersecurity",
            "data analysis",
            "IT support",
            "technical support",
            "data science",
            "information systems",
            "digital transformation",
            "cloud computing",
            "AI",
            "machine learning",
            "data engineering",
            "data visualization",
            "data architecture",
            "data security",
            "data governance",
        ],
    },
    "insinoori_tieto_ja_viestintatekniikka": {
        "name": "Insinööri (AMK), tieto- ja viestintätekniikka",
        "fields": ["Insinööri (AMK), tieto- ja viestintätekniikka"],
        "relevant_industries": [
            "technology",
            "software",
            "consulting",
            "finance",
            "healthcare",
            "education",
            "telecommunications",
            "IT",
            "information technology",
            "information systems",
            "information security",
            "information management",
        ],
        "relevant_roles": [
            "software development",
            "software engineering",
            "web development",
            "mobile development",
            "full stack development",
            "front end development",
            "back end development",
            "mobile app development",
            "web app development",
            "programming",
            "system administration",
            "database management",
            "network administration",
            "cybersecurity",
            "data analysis",
            "IT support",
            "technical support",
            "data science",
            "information systems",
            "digital transformation",
            "cloud computing",
            "AI",
            "machine learning",
            "data engineering",
            "data visualization",
            "data architecture",
            "data security",
            "data governance",
        ],
    },
    "tradenomi_tietojenkasittely": {
        "name": "Tradenomi (AMK), tietojenkäsittely",
        "fields": ["Tradenomi (AMK), tietojenkäsittely"],
        "relevant_industries": [
            "technology",
            "software",
            "consulting",
            "finance",
            "healthcare",
            "education",
            "telecommunications",
            "IT",
            "information technology",
            "information systems",
            "information security",
            "information management",
        ],
        "relevant_roles": [
            "software development",
            "software engineering",
            "web development",
            "mobile development",
            "full stack development",
            "front end development",
            "back end development",
            "mobile app development",
            "web app development",
            "programming",
            "system administration",
            "database management",
            "network administration",
            "cybersecurity",
            "data analysis",
            "IT support",
            "technical support",
            "data science",
            "information systems",
            "digital transformation",
            "cloud computing",
            "AI",
            "machine learning",
            "data engineering",
            "data visualization",
            "data architecture",
            "data security",
            "data governance",
        ],
    },
    # Culture Degrees
    "medianomi_amk": {
        "name": "Medianomi (AMK)",
        "fields": ["Medianomi (AMK)"],
        "relevant_industries": [
            "media",
            "entertainment",
            "education",
            "arts",
            "culture",
            "broadcasting",
            "publishing",
        ],
        "relevant_roles": [
            "media production",
            "content creation",
            "teaching",
            "pedagogy",
            "cultural management",
            "arts administration",
            "creative direction",
            "multimedia design",
            "audio production",
            "visual arts",
            "performing arts",
        ],
    },
    "musiikkipedagogi_amk": {
        "name": "Musiikkipedagogi (AMK)",
        "fields": ["Musiikkipedagogi (AMK)"],
        "relevant_industries": [
            "media",
            "entertainment",
            "education",
            "arts",
            "culture",
            "broadcasting",
            "publishing",
        ],
        "relevant_roles": [
            "music education",
            "teaching",
            "pedagogy",
            "cultural management",
            "arts administration",
            "creative direction",
            "audio production",
            "performing arts",
        ],
    },
    "tanssinopettaja_amk": {
        "name": "Tanssinopettaja (AMK)",
        "fields": ["Tanssinopettaja (AMK)"],
        "relevant_industries": [
            "media",
            "entertainment",
            "education",
            "arts",
            "culture",
            "broadcasting",
            "publishing",
        ],
        "relevant_roles": [
            "dance instruction",
            "teaching",
            "pedagogy",
            "cultural management",
            "arts administration",
            "creative direction",
            "performing arts",
        ],
    },
    # Natural Resources Degrees
    "agrologi_amk_maaseutuelinkeinot": {
        "name": "Agrologi (AMK), maaseutuelinkeinot",
        "fields": ["Agrologi (AMK), maaseutuelinkeinot"],
        "relevant_industries": [
            "agriculture",
            "forestry",
            "environmental",
            "rural development",
            "food production",
            "sustainability",
        ],
        "relevant_roles": [
            "agricultural consulting",
            "rural development",
            "environmental management",
            "sustainable farming",
            "food production",
            "forestry management",
            "land use planning",
            "agricultural technology",
            "environmental assessment",
            "rural business development",
        ],
    },
    # Business Administration Degrees
    "bachelor_of_business_administration_international_business": {
        "name": "Bachelor of Business Administration (BBA), International Business",
        "fields": ["Bachelor of Business Administration (BBA), International Business"],
        "relevant_industries": [
            "finance",
            "marketing",
            "consulting",
            "retail",
            "manufacturing",
            "technology",
            "international trade",
        ],
        "relevant_roles": [
            "marketing",
            "sales",
            "finance",
            "accounting",
            "management",
            "consulting",
            "business development",
            "strategy",
            "operations",
            "human resources",
            "international business",
            "trade",
            "logistics",
            "supply chain management",
            "entrepreneurship",
            "business analysis",
            "project management",
            "Marketing Assistant /Coordinator /Manager/Specialist",
            "Account Manager, Key Account Manager",
            "Sales Assistant/ Coordinator/ Manager",
            "Customer Service Manager",
            "Sales Operations Specialist",
            "Export Manager, Import Manager",
            "Logistics specialist",
        ],
    },
    "tradenomi_amk_liiketalous": {
        "name": "Tradenomi (AMK), liiketalous",
        "fields": ["Tradenomi (AMK), liiketalous"],
        "relevant_industries": [
            "finance",
            "marketing",
            "consulting",
            "retail",
            "manufacturing",
            "technology",
            "international trade",
        ],
        "relevant_roles": [
            "marketing",
            "sales",
            "finance",
            "accounting",
            "management",
            "consulting",
            "business development",
            "strategy",
            "operations",
            "human resources",
            "international business",
            "trade",
            "logistics",
            "supply chain management",
            "entrepreneurship",
            "business analysis",
            "project management",
            "Marketing Assistant /Coordinator /Manager/Specialist",
            "Account Manager, Key Account Manager",
            "Sales Assistant/ Coordinator/ Manager",
            "Customer Service Manager",
            "Sales Operations Specialist",
            "Export Manager, Import Manager",
            "Logistics specialist",
        ],
    },
    "tradenomi_amk_liiketalous_verkkokoulutus": {
        "name": "Tradenomi (AMK), liiketalous, verkkokoulutus",
        "fields": ["Tradenomi (AMK), liiketalous, verkkokoulutus"],
        "relevant_industries": [
            "finance",
            "marketing",
            "consulting",
            "retail",
            "manufacturing",
            "technology",
            "international trade",
        ],
        "relevant_roles": [
            "marketing",
            "sales",
            "finance",
            "accounting",
            "management",
            "consulting",
            "business development",
            "strategy",
            "operations",
            "human resources",
            "international business",
            "trade",
            "logistics",
            "supply chain management",
            "entrepreneurship",
            "business analysis",
            "project management",
            "Marketing Assistant /Coordinator /Manager/Specialist",
            "Account Manager, Key Account Manager",
            "Sales Assistant/ Coordinator/ Manager",
            "Customer Service Manager",
            "Sales Operations Specialist",
            "Export Manager, Import Manager",
            "Logistics specialist",
        ],
    },
    # Healthcare Degrees
    "bachelor_of_health_care_nursing": {
        "name": "Bachelor of Health Care, Nursing",
        "fields": ["Bachelor of Health Care, Nursing"],
        "relevant_industries": [
            "healthcare",
            "pharmaceuticals",
            "medical devices",
            "public health",
            "social services",
            "rehabilitation",
        ],
        "relevant_roles": [
            "patient care",
            "clinical work",
            "health administration",
            "research",
            "public health",
            "medical support",
            "healthcare management",
            "nursing",
            "social work",
            "rehabilitation",
            "medical technology",
            "health promotion",
            "emergency care",
            "maternal care",
            "optical care",
            "radiology",
            "dental hygiene",
        ],
    },
    "bioanalyytikko_amk": {
        "name": "Bioanalyytikko (AMK)",
        "fields": ["Bioanalyytikko (AMK)"],
        "relevant_industries": [
            "healthcare",
            "pharmaceuticals",
            "medical devices",
            "public health",
            "social services",
            "rehabilitation",
        ],
        "relevant_roles": [
            "patient care",
            "clinical work",
            "health administration",
            "research",
            "public health",
            "medical support",
            "healthcare management",
            "medical technology",
            "health promotion",
        ],
    },
    "ensihoitaja_amk": {
        "name": "Ensihoitaja (AMK)",
        "fields": ["Ensihoitaja (AMK)"],
        "relevant_industries": [
            "healthcare",
            "pharmaceuticals",
            "medical devices",
            "public health",
            "social services",
            "rehabilitation",
        ],
        "relevant_roles": [
            "patient care",
            "clinical work",
            "health administration",
            "research",
            "public health",
            "medical support",
            "healthcare management",
            "emergency care",
            "health promotion",
        ],
    },
    "fysioterapeutti_amk": {
        "name": "Fysioterapeutti (AMK)",
        "fields": ["Fysioterapeutti (AMK)"],
        "relevant_industries": [
            "healthcare",
            "pharmaceuticals",
            "medical devices",
            "public health",
            "social services",
            "rehabilitation",
        ],
        "relevant_roles": [
            "patient care",
            "clinical work",
            "health administration",
            "research",
            "public health",
            "medical support",
            "healthcare management",
            "rehabilitation",
            "medical technology",
            "health promotion",
        ],
    },
    "katilo_amk": {
        "name": "Kätilö (AMK)",
        "fields": ["Kätilö (AMK)"],
        "relevant_industries": [
            "healthcare",
            "pharmaceuticals",
            "medical devices",
            "public health",
            "social services",
            "rehabilitation",
        ],
        "relevant_roles": [
            "patient care",
            "clinical work",
            "health administration",
            "research",
            "public health",
            "medical support",
            "healthcare management",
            "maternal care",
            "health promotion",
        ],
    },
    "optometristi_amk": {
        "name": "Optometristi (AMK)",
        "fields": ["Optometristi (AMK)"],
        "relevant_industries": [
            "healthcare",
            "pharmaceuticals",
            "medical devices",
            "public health",
            "social services",
            "rehabilitation",
        ],
        "relevant_roles": [
            "patient care",
            "clinical work",
            "health administration",
            "research",
            "public health",
            "medical support",
            "healthcare management",
            "optical care",
            "health promotion",
        ],
    },
    "rontgenhoitaja_amk": {
        "name": "Röntgenhoitaja (AMK)",
        "fields": ["Röntgenhoitaja (AMK)"],
        "relevant_industries": [
            "healthcare",
            "pharmaceuticals",
            "medical devices",
            "public health",
            "social services",
            "rehabilitation",
        ],
        "relevant_roles": [
            "patient care",
            "clinical work",
            "health administration",
            "research",
            "public health",
            "medical support",
            "healthcare management",
            "radiology",
            "medical technology",
            "health promotion",
        ],
    },
    "sairaanhoitaja_amk": {
        "name": "Sairaanhoitaja (AMK)",
        "fields": ["Sairaanhoitaja (AMK)"],
        "relevant_industries": [
            "healthcare",
            "pharmaceuticals",
            "medical devices",
            "public health",
            "social services",
            "rehabilitation",
        ],
        "relevant_roles": [
            "patient care",
            "clinical work",
            "health administration",
            "research",
            "public health",
            "medical support",
            "healthcare management",
            "nursing",
            "social work",
            "rehabilitation",
            "medical technology",
            "health promotion",
            "emergency care",
            "maternal care",
            "optical care",
            "radiology",
            "dental hygiene",
        ],
    },
    "sosionomi_amk": {
        "name": "Sosionomi (AMK)",
        "fields": ["Sosionomi (AMK)"],
        "relevant_industries": [
            "healthcare",
            "pharmaceuticals",
            "medical devices",
            "public health",
            "social services",
            "rehabilitation",
        ],
        "relevant_roles": [
            "patient care",
            "clinical work",
            "health administration",
            "research",
            "public health",
            "medical support",
            "healthcare management",
            "social work",
            "rehabilitation",
            "health promotion",
        ],
    },
    "suuhygienisti_amk": {
        "name": "Suuhygienisti (AMK)",
        "fields": ["Suuhygienisti (AMK)"],
        "relevant_industries": [
            "healthcare",
            "pharmaceuticals",
            "medical devices",
            "public health",
            "social services",
            "rehabilitation",
        ],
        "relevant_roles": [
            "patient care",
            "clinical work",
            "health administration",
            "research",
            "public health",
            "medical support",
            "healthcare management",
            "dental hygiene",
            "health promotion",
        ],
    },
    "terveydenhoitaja_amk": {
        "name": "Terveydenhoitaja (AMK)",
        "fields": ["Terveydenhoitaja (AMK)"],
        "relevant_industries": [
            "healthcare",
            "pharmaceuticals",
            "medical devices",
            "public health",
            "social services",
            "rehabilitation",
        ],
        "relevant_roles": [
            "patient care",
            "clinical work",
            "health administration",
            "research",
            "public health",
            "medical support",
            "healthcare management",
            "health promotion",
        ],
    },
    "toimintaterapeutti_amk": {
        "name": "Toimintaterapeutti (AMK)",
        "fields": ["Toimintaterapeutti (AMK)"],
        "relevant_industries": [
            "healthcare",
            "pharmaceuticals",
            "medical devices",
            "public health",
            "social services",
            "rehabilitation",
        ],
        "relevant_roles": [
            "patient care",
            "clinical work",
            "health administration",
            "research",
            "public health",
            "medical support",
            "healthcare management",
            "rehabilitation",
            "medical technology",
            "health promotion",
        ],
    },
    # Engineering Degrees
    "bachelor_of_engineering_energy_and_environmental_engineering": {
        "name": "Bachelor of Engineering, Energy and Environmental Engineering",
        "fields": ["Bachelor of Engineering, Energy and Environmental Engineering"],
        "relevant_industries": [
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "energy engineering",
            "environmental engineering",
            "automation",
            "building technology",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "bachelor_of_engineering_mechanical_engineering": {
        "name": "Bachelor of Engineering, Mechanical Engineering",
        "fields": ["Bachelor of Engineering, Mechanical Engineering"],
        "relevant_industries": [
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "mechanical engineering",
            "automation",
            "building technology",
            "construction management",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "insinoori_amk_energia_ja_ymparistotekniikka": {
        "name": "Insinööri (AMK), energia- ja ympäristötekniikka",
        "fields": ["Insinööri (AMK), energia- ja ympäristötekniikka"],
        "relevant_industries": [
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "energy engineering",
            "environmental engineering",
            "automation",
            "building technology",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "insinoori_amk_konetekniikka": {
        "name": "Insinööri (AMK), konetekniikka",
        "fields": ["Insinööri (AMK), konetekniikka"],
        "relevant_industries": [
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "mechanical engineering",
            "automation",
            "building technology",
            "construction management",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "insinoori_amk_sahko_ja_automaatiotekniikka": {
        "name": "Insinööri (AMK), sähkö- ja automaatiotekniikka",
        "fields": ["Insinööri (AMK), sähkö- ja automaatiotekniikka"],
        "relevant_industries": [
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "electrical engineering",
            "automation",
            "building technology",
            "construction management",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "insinoori_amk_talotekniikka": {
        "name": "Insinööri (AMK), talotekniikka",
        "fields": ["Insinööri (AMK), talotekniikka"],
        "relevant_industries": [
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "building technology",
            "construction management",
            "architecture",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "insinoori_amk_rakennus_ja_yhdyskuntatekniikka": {
        "name": "Insinööri (AMK), rakennus- ja yhdyskuntatekniikka",
        "fields": ["Insinööri (AMK), rakennus- ja yhdyskuntatekniikka"],
        "relevant_industries": [
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "building technology",
            "construction management",
            "architecture",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "rakennusarkkitehti_amk": {
        "name": "Rakennusarkkitehti (AMK)",
        "fields": ["Rakennusarkkitehti (AMK)"],
        "relevant_industries": [
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "building technology",
            "construction management",
            "architecture",
            "sustainable design",
            "energy efficiency",
        ],
    },
    "rakennusmestari_amk": {
        "name": "Rakennusmestari (AMK)",
        "fields": ["Rakennusmestari (AMK)"],
        "relevant_industries": [
            "manufacturing",
            "construction",
            "technology",
            "automotive",
            "aerospace",
            "energy",
            "environmental",
            "building services",
        ],
        "relevant_roles": [
            "design",
            "development",
            "testing",
            "maintenance",
            "project management",
            "research",
            "quality control",
            "technical support",
            "system administration",
            "building technology",
            "construction management",
            "architecture",
            "sustainable design",
            "energy efficiency",
        ],
    },
    # General Studies (fallback)
    "general": {
        "name": "General Studies",
        "fields": [
            "Liberal Arts",
            "General Studies",
            "Interdisciplinary Studies",
        ],
        "relevant_industries": ["any"],
        "relevant_roles": ["any"],
    },
}
