repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      # Step 1: Run the linter with fixes (excluding import sorting)
      - id: ruff
        name: "ruff-lint"
        args: [--fix, --exit-non-zero-on-fix]
        # Ignores I rules to separate linting from import sorting

      # Step 2: Sort imports (matches `ruff check --select I --fix`)
      - id: ruff
        name: "ruff-sort-imports"
        args: [--select, "I", --fix, --exit-non-zero-on-fix]
        # Selects only I (import sorting) rules and fixes them

      # Step 3: Format (matches `ruff format`)
      - id: ruff-format
        name: "ruff-format"
        # No args needed unless overriding defaults